"""Regenerate lib/tools/airports_data.py from OurAirports (public domain).

Run by hand; the output is committed. Shipped as a Python module rather than
a JSON file because Vercel's Python builder traces imports, not data files —
a .json would need a vercel.json includeFiles change to survive the bundle.

    python scripts/build_airports.py
"""

import csv
import io
import pathlib

import httpx

URL = "https://davidmegginson.github.io/ourairports-data/airports.csv"
OUT = pathlib.Path(__file__).resolve().parents[1] / "lib" / "tools" / "airports_data.py"

HEADER = '''"""Generated by scripts/build_airports.py — do not edit by hand.

Source: OurAirports (public domain). Large and medium airports that have an
IATA code and scheduled service. Tuple order: (name, city, country, lat, lon).
"""

AIRPORTS = {
'''


def main() -> None:
    response = httpx.get(URL, timeout=180, follow_redirects=True)
    response.raise_for_status()
    rows = list(csv.DictReader(io.StringIO(response.text)))

    keep = [
        row for row in rows
        if row["iata_code"]
        and row["type"] in ("large_airport", "medium_airport")
        and row["scheduled_service"] == "yes"
    ]

    lines = [HEADER]
    for row in sorted(keep, key=lambda r: r["iata_code"]):
        entry = (
            row["name"],
            row["municipality"] or None,
            row["iso_country"],
            round(float(row["latitude_deg"]), 4),
            round(float(row["longitude_deg"]), 4),
        )
        lines.append(f"    {row['iata_code']!r}: {entry!r},\n")
    lines.append("}\n")

    OUT.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {OUT} with {len(keep)} airports")


if __name__ == "__main__":
    main()
